# Generated by Django 4.0 on 2023-08-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_userprofile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
