# Generated by Django 4.0 on 2023-08-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
